# Change these first
owner: maneckeb # Your GitHub organization or username, where this repository lives
repo: easy-interface-upptime # The name of this repository

sites:
  - name: Easy-Interface
    url: https://www.easy-interface.com
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /easy-interface-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Uptime monitor of Easy-interface.com"
  introMessage: 
  navbar:
    - title: Status
      href: /
    

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
